### ISSUE TITLE
Instructions.md

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed-nest#1]
In `plumed-nest/Contribute.html` we ask to contribute a file `Instructions.md` in the zip file. I would prefer to allow to include instructions in our repository (or in the form).

The reason is that people might want to link zip files from somewhere else (e.g. SI of a published paper) and might not even have the possibility to change them.

**Comment by maxbonomi** [comment]
Good point. We can make a text field (with more space) in the current form or maybe allow uploading a file. Will check

**Comment by maxbonomi** [comment]
I put a text form for instructions. let me know what you think.
Also, currently the data provided in the form is sent via email (currently to me,
eventually to plumed.nest@gmail.com). It is then one of us who prepare the *.yml
file for plumed-nest with all the fields sent in the email.
This is a bit sub-optimal, but unfortunately Gihub Sites is quite static.
Finally, I would like us to buy the domain www.plumed-nest.org

Cheers

**Comment by GiovanniBussi** [comment]
It should be easy to construct the yml automatically from the email txt, so
I think it's ok
